server {
    listen 80;
    server_name localhost;

    # Static UI Files
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # Pass dynamic API routes to the backend container
    location ~ ^/(inventory|orders|reports) {
        proxy_pass http://web_backend:5000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
